apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: shippingstore
  namespace: default
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "false"